### ISSUE TITLE
Page confusing readers by mixing up terminologies

### ISSUE THREAD

**Issue by norpol** [mhausenblas/canihaznonprivilegedcontainers.info#8]
This page is confusing. Docker `--privileged` (which is even referred in the docs) is something different than running as `root`, which has fewer [capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities).

A good summary for the capabilities is this [page](https://www.redhat.com/en/blog/secure-your-containers-one-weird-trick).

Depending on how you are using Docker those capabilities can be a security issue, but won't be one per-se.

**Comment by mhausenblas** [comment]
PR it to fix it?
